[package]
name = "wip-llvm"
description = "An LLVM backend for Wip, as textual IR that clang compiles"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
wip-syntax.workspace = true
wip-hir.workspace = true
wip-mir.workspace = true
rustc-hash.workspace = true
gimli.workspace = true
object = { workspace = true, features = ["build"] }
